### ISSUE TITLE
Need more threads in callbacker for miner

### ISSUE THREAD

**Issue by JDong820** [NosotrosNueces/mcc#72]
I'm working on a miner bot (https://github.com/NosotrosNueces/mcc/tree/miner). I want to use semaphores to handle mining block update feedback.

However, callbacker is a single thread that runs all the function callbacks in it's own thread. That means sem_wait will block the entire callbacker thread. This is the problem where we can't do too much in handlers due to the single threaded async callbacker model.

I think we should consider having callbacker to spawn new threads for each callback handler function we call. This makes coding handlers safer and more straightforward.

+, we should spawn new threads for each callback handler
 * Coding handlers is much easier.
 * Handlers will never block each other.

-, we should keep the single-threaded async model
 * We will have to use mutexes for shared state (any bot data).
 * It will heavily(?) complicate the engine.
 
I'm actually leaning towards spawning new threads in the handlers to handle stuff and write multithreaded code in the bots themselves, but wanted to raise this up for discussion. Verdict?

**Comment by JDongian** [comment]
Nothing is wrong, so closing.
