### ISSUE TITLE
Undefined Behavior

### ISSUE THREAD

**Issue by SrsBusiness** [NosotrosNueces/mcc#92]
Beware of casting unaligned pointers:

```c
void f(void *ptr) {
    int x = *(int *)ptr; // this is undefined behavior
}

void foo(char *ptr) {
    long x = *(long *)ptr; // this is also wrong
}
```
Use memcpy.

Also pointer arithmetic on void pointers is not well defined. Cast it to a pointer to a word of defined size first, e.g.
```c
void f(void *ptr) {
    char *cptr = ptr;
   cptr++;
   /* ...etc */
}
```

**Comment by JDongian** [comment]
We've fixed all these issues as far as I know, so I'm closing this.
