### ISSUE TITLE
Including Other Projects

### ISSUE THREAD

**Issue by SrsBusiness** [NosotrosNueces/mcc#94]
How should we go about including other projects into mcc? Are we just gonna clone it into our src/ directory?

**Comment by JDongian** [comment]
Depends on licensing and size of code base. For NBT, I would suggest a separate NBT directory under root. Other libraries will be considered case-by-case as mcc is licensed GPL2, a copyleft license and may not be compatible with all licenses.

**Comment by JDongian** [comment]
No definite answer, we go on a case-by-case basis.
